// The backend's golden vectors, verified here. testdata/grainhack_results_golden.json
// is a byte-for-byte copy of Grainlify-Backend's
// internal/grainhack/testdata/grainhack_results_golden.json, generated by its
// statement_test.go. If the backend regenerates it (a deliberate, coordinated
// change of the canonical form), copy it here again; this test failing on the
// copy means the two sides no longer agree on what a statement is.
//
// The signer half of the cross-check is services/signer/test/grainhack-golden.test.ts.

import { describe, expect, it } from 'vitest';
import { canonicalJson, RESULTS_DOMAIN, statementSha256, verifyStatement, type ResultsStatement } from '../src/grainhack-statement.ts';
import { golden } from './grainhack-golden.ts';
import { resultsKey } from './grainhack-support.ts';


describe("the backend's golden results statements", () => {
  it('has both vectors, under this domain and key', () => {
    expect(golden.domain).toBe(RESULTS_DOMAIN);
    expect(golden.vectors.map((v) => v.name)).toEqual(['basic', 'supersedes_and_escaping']);
    expect(resultsKey(Buffer.from(golden.signing_key_seed_b64, 'base64')).pubkeyB64).toBe(golden.public_key_b64);
  });

  for (const v of golden.vectors) {
    it(`${v.name}: verifies, is canonical, and signs to the same bytes here`, () => {
      const r = verifyStatement(v.statement, v.signature_b64, golden.public_key_b64);
      expect(r).toMatchObject({ ok: true, sha256: v.statement_sha256 });
      expect(statementSha256(v.statement)).toBe(v.statement_sha256);
      // Parsing and re-serialising gives the backend's exact string back.
      expect(canonicalJson(JSON.parse(v.statement))).toBe(v.statement);
      // Ed25519 is deterministic: the same key signs the same bytes to the same signature.
      expect(resultsKey(Buffer.from(golden.signing_key_seed_b64, 'base64')).sign(v.statement)).toBe(v.signature_b64);
      // One byte of difference anywhere is refused.
      expect(verifyStatement(v.statement.replace('"v":1', '"v":2'), v.signature_b64, golden.public_key_b64).ok).toBe(false);
    });
  }

  it('supersedes_and_escaping: the escapes, the largest safe id and the superseded statement come through as the backend meant', () => {
    const v = golden.vectors.find((x) => x.name === 'supersedes_and_escaping')!;
    const r = verifyStatement(v.statement, v.signature_b64, golden.public_key_b64);
    if (!r.ok) throw new Error(r.reason);
    const s: ResultsStatement = r.statement;
    expect(s.hackathon_name).toBe('Grain"Hack" — café <&> \\ \n\t\u0001\u007f   ✓ 🌾');
    expect(s.lines.map((l) => [l.github_user_id, l.status])).toEqual([[1, 'held_kyc'], [2, 'payable'], [Number.MAX_SAFE_INTEGER, 'payable']]);
    expect(s.supersedes).toBe('11111111-1111-4111-8111-111111111111');
    expect(s.network).toBe('solana-mainnet');
    // Written as-is, not escaped: <, >, &, U+2028 and the emoji; escaped: the quote, the backslash and the control characters.
    expect(v.statement).toContain('<&>');
    expect(v.statement).toContain(' ');
    expect(v.statement).toContain('\\"Hack\\"');
    expect(v.statement).toContain('\\\\ \\n\\t\\u0001');
  });
});
