[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bounty_escrow = "6MXnJKEdt1YPUZoxT8LkhL7bVshB68o4mXJiSfD8spDA"

[programs.devnet]
bounty_escrow = "6MXnJKEdt1YPUZoxT8LkhL7bVshB68o4mXJiSfD8spDA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx --test tests/*.test.ts"
