import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface X402ErrorItem {
  status: number;
  type: string;
  message: string;
  provenance: string;
}

export interface BalanceEnvelopeFixture {
  provenance: string;
  header: string;
  json: Record<string, unknown>;
  check_order: string[];
  gotcha: string;
}

export interface X402ErrorsFixture {
  captured_at: string;
  endpoint: string;
  note: string;
  errors: Record<string, X402ErrorItem>;
  balance_envelope?: BalanceEnvelopeFixture;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const REPO_ROOT = resolve(__dirname, '..');
export const DEFAULT_FIXTURE_PATH = resolve(REPO_ROOT, 'fixtures/usepod/x402-errors.json');
export const DEFAULT_TARGET_PATH = resolve(REPO_ROOT, 'docs/X402-ERRORS.md');

/**
 * Renders the markdown document for x402 error reference from fixture data.
 */
export function renderDoc(fixture: X402ErrorsFixture): string {
  const lines: string[] = [];

  lines.push('# UsePod x402 Error Reference');
  lines.push('');
  lines.push('<!-- Auto-generated by scripts/generate-x402-errors-doc.ts. Do not edit directly. -->');
  lines.push('');
  lines.push(
    `Reference of error responses returned by the UsePod x402 gateway endpoint (\`${fixture.endpoint}\`), recorded in [\`fixtures/usepod/x402-errors.json\`](../fixtures/usepod/x402-errors.json).`
  );
  lines.push('');
  lines.push(`- **Captured at:** \`${fixture.captured_at}\``);
  lines.push(`- **Endpoint:** \`${fixture.endpoint}\``);
  lines.push('');
  lines.push('## Provenance');
  lines.push('');
  lines.push('The gateway error catalogue distinguishes established facts from defensive mock behaviours:');
  lines.push('');
  lines.push('- **`observed`**: Returned by the live gateway to an unpaid probe (cost $0). Established fact.');
  lines.push('- **`assumed`**: Not yet seen live; the mock gateway uses this text defensively until confirmed by a paid spike.');
  lines.push('');

  const entries = Object.entries(fixture.errors);
  const observed = entries.filter(([_, e]) => e.provenance.toLowerCase().includes('observed'));
  const assumed = entries.filter(([_, e]) => e.provenance.toLowerCase().includes('assumed'));
  const other = entries.filter(
    ([_, e]) => !e.provenance.toLowerCase().includes('observed') && !e.provenance.toLowerCase().includes('assumed')
  );

  function renderTable(items: [string, X402ErrorItem][]): void {
    lines.push('| Key | HTTP Status | Type | Provenance | Message |');
    lines.push('| :--- | :--- | :--- | :--- | :--- |');
    for (const [key, err] of items) {
      lines.push(`| \`${key}\` | \`${err.status}\` | \`${err.type}\` | \`${err.provenance}\` | \`${err.message}\` |`);
    }
    lines.push('');
  }

  lines.push(`## Observed Errors (${observed.length})`);
  lines.push('');
  lines.push('Errors confirmed by live gateway probes:');
  lines.push('');
  renderTable(observed);

  lines.push(`## Assumed Errors (${assumed.length})`);
  lines.push('');
  lines.push('Errors not yet observed live; handled defensively in the mock gateway:');
  lines.push('');
  renderTable(assumed);

  if (other.length > 0) {
    lines.push(`## Other Errors (${other.length})`);
    lines.push('');
    renderTable(other);
  }

  if (fixture.balance_envelope) {
    const env = fixture.balance_envelope;
    lines.push('## Balance Envelope Reference');
    lines.push('');
    lines.push(`- **Provenance:** \`${env.provenance}\``);
    lines.push(`- **Header:** \`${env.header}\``);
    lines.push('');
    lines.push('### Expected Payload JSON Format');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(env.json, null, 2));
    lines.push('```');
    lines.push('');
    if (env.check_order && env.check_order.length > 0) {
      lines.push('### Verification Check Order');
      lines.push('');
      for (let i = 0; i < env.check_order.length; i++) {
        lines.push(`${i + 1}. \`${env.check_order[i]}\``);
      }
      lines.push('');
    }
    if (env.gotcha) {
      lines.push('### Gotchas');
      lines.push('');
      lines.push(`> ${env.gotcha}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Loads the fixture, renders the doc, and optionally writes to disk.
 */
export function generateDoc(options?: {
  fixturePath?: string;
  targetPath?: string;
  write?: boolean;
}): { content: string; targetPath: string } {
  const fixturePath = options?.fixturePath ?? DEFAULT_FIXTURE_PATH;
  const targetPath = options?.targetPath ?? DEFAULT_TARGET_PATH;
  const shouldWrite = options?.write ?? true;

  const raw = readFileSync(fixturePath, 'utf8');
  const fixture = JSON.parse(raw) as X402ErrorsFixture;
  const content = renderDoc(fixture);

  if (shouldWrite) {
    writeFileSync(targetPath, content, 'utf8');
  }

  return { content, targetPath };
}

// CLI execution
if (process.argv[1] && resolve(process.argv[1]) === resolve(__filename)) {
  const { targetPath } = generateDoc({ write: true });
  console.log(`Generated x402 error reference doc at: ${targetPath}`);
}
